# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BwtcCoffeeShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseCore'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Messaging'

  # Pods for BwtcCoffeeShop

end
