# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'BwtcCoffeeShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'SDWebImage'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwift'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'



    

  # Pods for BwtcCoffeeShop

end
